# Generated by Django 5.1.4 on 2024-12-11 08:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('contact_type', models.CharField(choices=[('Ребенок', 'Ребенок'), ('Студент', 'Студент'), ('Человек', 'Человек'), ('Говорящий', 'Говорящий'), ('Преподаватель', 'Преподаватель')], default='Человек', max_length=64, verbose_name='Уровень владения языком')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электронной почты')),
                ('level', models.CharField(choices=[('Ребенок', 'Ребенок'), ('Студент', 'Студент'), ('Человек', 'Человек'), ('Говорящий', 'Говорящий'), ('Преподаватель', 'Преподаватель')], default='Человек', max_length=64, verbose_name='Уровень владения языком')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
